name: radio_life
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.56+09

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  #region UI Stuff
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.1
  intl_utils: ^2.8.0
  uiblock: ^2.0.2
  auto_size_text: ^3.0.0
  shimmer: ^2.0.0
  flutter_native_splash: ^2.2.5
  layout: ^1.0.2
  websafe_svg: ^2.1.2+1
  responsive_builder: ^0.4.2
  flutter_speed_dial: ^6.0.0
  flutter_holo_date_picker: ^1.0.3
  persistent_bottom_nav_bar: ^4.0.2
  lottie: ^1.3.0
#  image_picker: ^0.8.5+3
  infinite_scroll_pagination: ^3.2.0
  #endregion

  #region Local
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15
  shared_preferences_web: ^2.0.4
  #endregion

  #region Device
  qr_code_scanner: ^1.0.1
  wifi_iot: ^0.3.16
#  connectivity_plus: ^4.0.1
  app_settings: ^4.1.8
  wifi_scan: ^0.4.0+1
  #endregion

  #region Arch and State Management
  get: ^4.6.5
  package_info: ^2.0.2
  lint: ^1.8.2
  #endregion

  #region Dependency Injection
#  injectable: ^1.5.3
  get_it: ^7.2.0
  #endregion

  #region Network
  graphql_flutter: ^5.0.0-nullsafety.1
  graphql: ^5.0.0-nullsafety.1
  dio: ^5.0.0
#  oauth_dio: ^0.2.7
  #endregion

  #region Dart and Others
  equatable: ^2.0.3
  tuple: ^2.0.0
  intl: ^0.18.0
  share: ^2.0.4
  flinq: ^2.0.2
  flutter_blue_plus: ^1.7.1
  # permission_handler: ^10.4.3
  connectivity: ^3.0.6
  universal_io: ^2.0.4
  #endregion

  #region Utils
  flutter_keyboard_visibility: ^5.3.0
  #endregion

  #region Artemis
  json_annotation: ^4.6.0
  gql: ^0.13.1
  #endregion

  #region Firebase
  firebase_core: ^1.19.2
  firebase_crashlytics: ^2.8.5
  #endregion

  file: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
#  fastlane: ^2.4.1
#  build_runner: ^2.2.0
#  artemis: ^6.18.4
#  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/loading/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  main_locale: en

flutter_native_splash:
  color: "#FA4B86"
  image: assets/images/white_monochrome_logo_vertical_splash_screen.png
  android_gravity: center
  ios_content_mode: center

#dependency_overrides:
#  platform: ^3.1.0