name: Distribute Android and iOs apps

on:
  push:
    branches:
      - main
      
jobs:
  deploy_android:
    name: Deploy Android production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1.62.0
        with:
          ruby-version: '2.7'
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Install NDK
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;22.0.7026061" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_secrets.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Set up Flutter environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release -t lib/main.dart
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      - name: Run Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: android_dev
          subdirectory: android
        env:
          FIREBASE_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
