name: Distribute Android and iOs apps

on:
  push:
    branches:
      - "ios_release"

jobs:
#  deploy_android_dev:
#    name: Deploy Android dev build to Firebase App Distribution
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ruby/setup-ruby@v1.62.0
#        with:
#          ruby-version: '2.7'
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '11.x'
#      - name: Install NDK
#        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;22.0.7026061" --sdk_root=${ANDROID_SDK_ROOT}
#      - name: Decrypt Android keys
#        run: sh ./.github/scripts/decrypt_android_secrets.sh
#        env:
#          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
#      - name: Set up Flutter environment
#        uses: subosito/flutter-action@v1
#        with:
#          flutter-version: '3.0.5'
#      - run: flutter clean
#      - run: flutter pub get
#      - run: flutter build apk --release -t lib/main_dev.dart
#        env:
#          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
#          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
#      - name: Run Fastlane
#        uses: maierj/fastlane-action@v1.4.0
#        with:
#          lane: android_dev
#          subdirectory: android
#        env:
#          FIREBASE_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'
#          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'

  deploy_ios:
    name: Deploy beta build to TestFlight
    runs-on: macOS-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v3

      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: closed_beta
          subdirectory: ios

        env:
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          FASTLANE_USER: '${{ secrets.FASTLANE_USER }}'
          #FASTLANE_PASSWORD: '${{ secrets.FASTLANE_PASSWORD }}'
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION_NEW }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
          APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
          APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
          APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'