name: Distribute iOS App

on:
  push:
    branches:
      - "ios_release"


jobs:
  deploy:
    runs-on: macos-latest
steps:
  - uses: actions/checkout@v2
  - name: Select Xcode version
    run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
  - name: Bundle install
    run: cd ./ios && bundle install
  - name: Setup JDK
    uses: actions/setup-java@v1
    with:
      java-version: "12.x"
  - name: Setup flutter
    uses: subosito/flutter-action@v1
    with:
      flutter-version: "1.17.0"
      channel: "stable"
  - name: Install tools
    run: |
      flutter pub get
      cd ./ios && pod install
  - name: Deploy to TestFlight
    run: |
      cd ./ios && bundle exec fastlane beta
    env:
      APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
      DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
      DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
      DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
      FASTLANE_USER: '${{ secrets.FASTLANE_USER }}'
      #FASTLANE_PASSWORD: '${{ secrets.FASTLANE_PASSWORD }}'
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
      MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
      GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
      PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
      TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
      TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
      APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
      APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
      APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'
